module.exports = {
  "ALIVE_IMG": "https://raw.githubusercontent.com/Niko-AND-Janiya/ANJU-DATA/refs/heads/main/WhatsApp%20Image%202024-09-08%20at%209.00.17%20PM.jpeg",
  "PREFIX": ".",
  "AUTO_READ_STATUS": false,
  "MODE": "public",
  "BOT_NUMBER": "94727255904",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": true,
  "AUTO_VOICE": false,
  "AUTO_STICKER": false,
  "AUTO_REPLY": true,
  "AUTO_REACT": true,
  "WELCOME": true,
  "ANTI_BAD": true,
  "ANTI_BOT": true,
  "ANTI_LINK": false,
  "ALLWAYS_ONLINE": flse,
  "MOROCCO_BLOCK": true,
  "BTN_MSG": false,
  "OWNER_NAME": "MR NIPUN",
  "NEWS_JID": "1234567890@s.whatsapp.net",
  "AUTO_TYPING": true,
  "AUTO_RECORDING": true,
  "AUTO_NEWS": false,
  "OWNER_REACT": true,
  "EMOJI": "🏷"
};
